### ISSUE TITLE
ERROR: compilation failed for package 'compPLS'

### ISSUE THREAD

**Issue by zhoult135** [zdk123/compPLS#1]
I can't install the package under Windows via devtools due to undefined reference errors:

`> install_github('zdk123/compPLS')
Downloading GitHub repo zdk123/compPLS@master
from URL RL https://api.github.com/repos/zdk123/compPLS/zipball/master
Ins
Installing compPLS
"D:/Software/R-3.4.4/bin/i386/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/fengxin/AppData/Local/Temp/RtmpO2hFg2/devtoolsd2c020f74f74/zdk123-compPLS-5451b05"  \
  --library="D:/Software/R-3.4.4/library" --install-tests 

* installing *source* package 'compPLS' ...
** libs

*** arch - i386
no DLL was created
ERROR: compilation failed for package 'compPLS'
* removing 'D:/Software/R-3.4.4/library/compPLS'
In R CMD INSTALL
Installation failed: Command failed (1)`

**Comment by YJL900223** [comment]
I also can't install the package under Windows via devtools due to undefined reference errors:
> install_github('zdk123/compPLS')
Downloading GitHub repo zdk123/compPLS@master
√  checking for file 'C:\Users\Administrator.989F6F52MTNHTJA\AppData\Local\Temp\RtmpwBKSQQ\remotesdb07ccb4ba6\zdk123-compPLS-5451b05/DESCRIPTION'
-  preparing 'compPLS':
√  checking DESCRIPTION meta-information ...
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (583ms)
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'compPLS_1.0.tar.gz'
   
* installing *source* package 'compPLS' ...
** using staged installation
** libs

*** arch - i386
no DLL was created
ERROR: compilation failed for package 'compPLS'
* removing 'C:/Program Files/R/R-3.6.3/library/compPLS'
installation of package ��C:/Users/ADMINI~1.989/AppData/Local/Temp/RtmpwBKSQQ/filedb02d0e5233/compPLS_1.0.tar.gz�� had non-zero exit status

**Comment by zdk123** [comment]
try again, please!
